//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POOAlumnos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POOAlumnos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprete tecla para continuar ....
        /// </summary>
        internal static string ContProceso {
            get {
                return ResourceManager.GetString("ContProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige Opcion:.
        /// </summary>
        internal static string elegiropcion {
            get {
                return ResourceManager.GetString("elegiropcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra apellidos:.
        /// </summary>
        internal static string formApellidos {
            get {
                return ResourceManager.GetString("formApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra datos del Alumno:.
        /// </summary>
        internal static string formdatos {
            get {
                return ResourceManager.GetString("formdatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato por defecto Alumno : .
        /// </summary>
        internal static string formdatosdefecto {
            get {
                return ResourceManager.GetString("formdatosdefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoja opcion formato salida (Texto = 1, JSON = 2, XML = 3) o continue con la de defecto.
        /// </summary>
        internal static string formdatosparse {
            get {
                return ResourceManager.GetString("formdatosparse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra dni:.
        /// </summary>
        internal static string formDni {
            get {
                return ResourceManager.GetString("formDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra id:.
        /// </summary>
        internal static string formId {
            get {
                return ResourceManager.GetString("formId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entra name:.
        /// </summary>
        internal static string formName {
            get {
                return ResourceManager.GetString("formName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu aplicacion:.
        /// </summary>
        internal static string Litmenu {
            get {
                return ResourceManager.GetString("Litmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1- Crear alumno.
        /// </summary>
        internal static string menuAlum {
            get {
                return ResourceManager.GetString("menuAlum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2- Configuracion.
        /// </summary>
        internal static string menuConfig {
            get {
                return ResourceManager.GetString("menuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0- Salir aplicacion.
        /// </summary>
        internal static string menuSalir {
            get {
                return ResourceManager.GetString("menuSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningun formato correcto.
        /// </summary>
        internal static string NingunFormato {
            get {
                return ResourceManager.GetString("NingunFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opcion no valida .... escoja otra por favor.
        /// </summary>
        internal static string OpcionNoValida {
            get {
                return ResourceManager.GetString("OpcionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serializable.
        /// </summary>
        internal static string Serializable {
            get {
                return ResourceManager.GetString("Serializable", resourceCulture);
            }
        }
    }
}
